# Generated by Django 2.0b1 on 2017-11-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flickr_id', models.CharField(max_length=100)),
                ('secret', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('flickr_tags', models.CharField(blank=True, max_length=300)),
                ('processed', models.BooleanField(default=False)),
                ('url_sq', models.URLField(blank=True)),
                ('url_t', models.URLField(blank=True)),
                ('url_s', models.URLField(blank=True)),
                ('url_q', models.URLField(blank=True)),
                ('url_m', models.URLField(blank=True)),
                ('url_n', models.URLField(blank=True)),
                ('url_z', models.URLField(blank=True)),
                ('url_c', models.URLField(blank=True)),
                ('url_l', models.URLField(blank=True)),
                ('url_o', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('mid', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('synced', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='fgcv.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
