# Generated by Django 2.0b1 on 2017-11-03 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_imported',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='machine_tags',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
