# Generated by Django 2.0b1 on 2017-11-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0003_auto_20171103_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExifTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=300)),
                ('raw', models.CharField(blank=True, max_length=300)),
                ('clean', models.CharField(max_length=300)),
                ('tag', models.CharField(blank=True, max_length=300)),
                ('tagspace', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exiftag',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exif_tags', to='fgcv.Photo'),
        ),
    ]
