# Generated by Django 2.0b1 on 2017-11-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0004_auto_20171104_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exiftag',
            old_name='clean',
            new_name='pretty',
        ),
    ]
