# Generated by Django 2.0b1 on 2017-11-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0005_auto_20171104_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exiftag',
            name='pretty',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
