# Generated by Django 2.0b1 on 2017-11-05 15:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0006_auto_20171104_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='exposure',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exif',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exif', to='fgcv.Photo'),
        ),
    ]
