# Generated by Django 2.0b1 on 2017-11-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0007_auto_20171105_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exif',
            options={'verbose_name': 'EXIF', 'verbose_name_plural': 'EXIF'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
