# Generated by Django 2.0b1 on 2017-11-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgcv', '0008_auto_20171105_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exiftag',
            name='photo',
        ),
        migrations.DeleteModel(
            name='ExifTag',
        ),
    ]
